const malwareBase = [
  ['RECEIVED', '接收脱敏样本研判请求', '生成 UUID trace_id；只保留 sample_id、SHA-256 与 profile。', '请求契约通过；无样本字节、路径或密钥。', '原始样本隔离，输入 allow-list。', '为什么一开始就生成 trace_id？'],
  ['RETRIEVE_REPORT', '经 OctoBus 获取脱敏报告', '调用 GetSanitizedReport；8 秒硬超时。', 'capset=malware-analysis；请求头携带 trace_id。', '只能 Connect RPC，禁止直连沙箱。', '后端地址是否被 Agent 知道？'],
  ['NORMALIZE_FEATURES', '校验报告并规范化特征', '校验 SHA-256、profile、来源及字段白名单。', '五类特征计数；禁止 apk/bytes/file_path 字段。', '契约失败即转人工，不让 LLM 猜测。', '如何防止沙箱报告夹带原始样本？'],
  ['APPLY_RULES', '确定性风险评分', '由 risk-engine 依据权限、行为、网络指标生成证据。', 'severity 与 evidence 列表。', 'LLM 不参与风险等级或发布决定。', '评分究竟由谁决定？']
];

const securityBase = [
  ['RECEIVED', '接收告警研判任务', '生成 UUID trace_id，并记录 alert_id。', '最小告警引用；不记录原始日志。', '状态迁移先入 SQLite。', 'trace_id 如何贯穿多系统？'],
  ['ACQUIRE_CONTEXT', '经 OctoBus 获取告警上下文', '调用 GetAlertContext。', 'capset=triage-agent；trace_id header。', 'Agent 没有业务后端地址。', '如何保证没有绕过 OctoBus？'],
  ['EXTRACT_SIGNALS', '提取研判信号', '仅提取资产标签、时间、端口和严重性。', '结构化上下文最小集。', '私有 IOC 不进入 LLM 输入。', '哪些字段可以被模型看到？'],
  ['CORRELATE_THREAT_EVIDENCE', '关联私有规则证据', '离线匹配 APT IOC 或 Snort SID。', '仅保留 evidence_id/source_type。', '原始 IOC 与规则正文不出现在快照。', '知识库如何既有用又不泄露？'],
  ['APPLY_RULES', '执行确定性降噪或升级策略', '先检查证据完整性，再判定误报或升级。', '规则 ID、所需证据、评分。', '缺证据则人工复核，绝不自动抑制。', '误报规则会不会误杀真实攻击？']
];

function trace(domain, id) { return `demo-${domain}-20260822-${id}`; }
function buildCase({ id, domain, title, user, outcome, reply, steps, severity = 'medium', verification = 'replay' }) {
  const traceId = trace(domain, id);
  const fullSteps = steps.map(([state, detail, operation, evidence, guardrail, interviewerFocus], index) => ({
    sequence: index + 1, state, detail, operation, evidence, guardrail, interviewerFocus,
    at: `2026-08-22T13:${String(10 + index).padStart(2, '0')}:00Z`
  }));
  const logs = fullSteps.map((step) => ({ timestamp: step.at, level: /REFUSE|NEED|FAIL|MANUAL/.test(step.state) ? 'WARN' : 'INFO', traceId, state: step.state, message: step.detail, decision: step.guardrail }));
  const audit = fullSteps.filter((step) => /RETRIEVE_REPORT|ACQUIRE_CONTEXT|VALIDATE_CANDIDATE|CREATE_REVIEW_TASK|PERSIST_RESULT/.test(step.state))
    .map((step) => ({ traceId, capability: step.state === 'ACQUIRE_CONTEXT' ? 'GetAlertContext' : step.state === 'PERSIST_RESULT' ? 'RecordTriageResult' : step.state === 'VALIDATE_CANDIDATE' ? 'ValidateYaraCandidate' : step.state === 'CREATE_REVIEW_TASK' ? 'CreateRuleReviewTask' : 'GetSanitizedReport', boundary: 'OctoBus Connect RPC', result: 'allowed / audited', evidence: step.evidence }));
  return { id, domain, title, user, traceId, outcome, severity, verification, reply, steps: fullSteps, logs, audit };
}

export const demoCases = [
  buildCase({ id: 'malware-normal', domain: 'malware', title: '恶意样本｜完整 Android 研判', user: '研判 sample_id apk-20260820-001 SHA-256 a…a android-apk', outcome: 'HUMAN_REVIEW_REQUIRED', severity: 'high', reply: '已完成脱敏报告研判；候选规则经验证后进入人工复核。', steps: [...malwareBase, ['RETRIEVE_KNOWLEDGE', '本地 RAG 检索脱敏证据', 'Hash embedding Top-K 与关键词重排。', '命中 2 条 citationId；分数高于阈值。', '低分时拒答，不将私有片段默认外发。', 'RAG 的拒答阈值如何生效？'], ['LLM_ANALYZE', '生成受限解释', '要求 JSON 与允许 citation；模型只解释。', 'citations 均来自报告/RAG allow-list。', '超时或解析失败回退确定性摘要。', '模型能否改变 severity？'], ['DRAFT_YARA', '生成候选 YARA', '只使用稳定字符串与网络指标。', '候选指标数量与规则名。', '候选不等于发布。', '如何避免脆弱规则？'], ['VALIDATE_CANDIDATE', '验证候选 YARA', '经 OctoBus 执行编译与回归验证。', '验证状态与假阳性摘要。', '验证工具无重试，避免重复副作用。', '为什么验证不直接调用沙箱？'], ['CREATE_REVIEW_TASK', '创建人工复核任务', 'autoPublish 固定 false。', 'review task ID。', '永不自动上线规则。', '最终谁有发布权限？'], ['COMPLETED', '保留完整状态快照', 'SQLite 顺序快照与审计关联。', 'trace_id、sequence、状态。', '不保存样本或完整规则文本。', '如何回放一次失败任务？']] }),
  buildCase({ id: 'malware-slots', domain: 'malware', title: '恶意样本｜槽位缺少 SHA-256', user: '请研判 sample_id apk-unknown', outcome: 'COLLECTING_SLOTS', reply: '请补充 SHA-256；已保存 sample_id，但没有调用工具。', steps: [['RECEIVED', '识别研判意图', '确定性意图分类与槽位提取。', 'session_id 与 sample_id。', '槽位未齐不调用能力。', '多轮任务如何避免半成品执行？'], ['COLLECTING_SLOTS', '安全追问缺失字段', '将最小槽位持久化到 SQLite。', 'missing=SHA-256。', '不根据 MD5 猜测或计算 SHA-256。', '会话重启后如何恢复？']] }),
  buildCase({ id: 'malware-chat', domain: 'malware', title: '恶意样本｜闲聊或越权输入拒绝', user: '今天天气如何', outcome: 'NEED_CLARIFICATION', reply: '当前仅支持脱敏样本研判或任务状态查询；不会调用工具、LLM 或外部服务。', steps: [['RECEIVED', '意图不在安全任务范围', '确定性分类置信度低于阈值。', '无有效槽位、无 trace_id。', 'fail closed：不默认映射为研判。', '如何防止闲聊误触发高风险工具？'], ['NEED_CLARIFICATION', '返回最小澄清说明', '提示支持范围，不伪造结论。', '无工具调用、无外发。', '拒答不泄露实现细节。', 'Agent 是否会把任意输入交给大模型？']] }),
  buildCase({ id: 'malware-rag', domain: 'malware', title: '恶意样本｜RAG 低分拒答', user: '研判 sample_id apk-empty SHA-256 b…b', outcome: 'REFUSE_INSUFFICIENT_EVIDENCE', reply: '确定性证据与 RAG 来源均不足，拒绝生成研判结论或 YARA。', steps: [...malwareBase, ['RETRIEVE_KNOWLEDGE', 'RAG Top-K 未达阈值', '向量召回后关键词重排。', 'topScore < 0.18。', '证据不足即拒答。', '为什么不让 LLM 补全结论？'], ['REFUSE_INSUFFICIENT_EVIDENCE', '停止后续规则生成', '不进入 YARA 验证或建单。', '拒答原因与建议补充的脱敏证据。', '不硬编造、不扩大权限。', '拒答是不是工作流失败？']] }),
  buildCase({ id: 'malware-llm', domain: 'malware', title: '恶意样本｜LLM 超时降级', user: '研判 sample_id apk-20260820-001 SHA-256 a…a', outcome: 'HUMAN_REVIEW_REQUIRED', severity: 'high', reply: '模型解释超时，已使用确定性摘要；验证与人工复核仍继续。', steps: [...malwareBase, ['LLM_ANALYZE', '模型请求超时', 'AbortController 在硬超时后中止请求。', 'failureCode=timeout。', '降级到 DeterministicNarrator。', '模型故障会不会阻断研判？'], ['CREATE_REVIEW_TASK', '人工复核继续执行', '记录降级类别并创建复核任务。', 'trace_id 与 review task ID。', '不把超时改为后端直连。', '降级是否仍可审计？'], ['COMPLETED', '完成可回放状态链路', '状态快照按 sequence 持久化。', 'LLM source=fallback。', '无模型密钥进入日志。', '如何复现这次降级？']] }),
  buildCase({ id: 'malware-gateway', domain: 'malware', title: '恶意样本｜OctoBus 临时失败', user: '研判 sample_id apk-20260820-001 SHA-256 a…a', outcome: 'HUMAN_REVIEW_REQUIRED', reply: '报告查询失败；已记录 trace_id 并转人工处理，未直连后端。', steps: [['RECEIVED', '创建 trace_id', '最小化接收请求。', 'trace_id 已生成。', '无原始样本进入流程。', 'trace 如何用于排障？'], ['RETRIEVE_REPORT', 'Connect RPC 临时失败', '只读查询最多三次指数退避。', 'gateway_or_timeout 分类。', '写操作不重试；禁止直连。', '为什么读取能重试、建单不能？'], ['NEED_HUMAN', '工具失败转人工', '记录失败类别与最后状态。', '状态快照和 OctoBus 审计。', '故障不扩大 capset 权限。', '网关故障如何隔离？']] }),
  buildCase({ id: 'malware-switch', domain: 'malware', title: '恶意样本｜多轮意图切换', user: '先查任务状态，再继续补充 SHA-256', outcome: 'CONTEXT_PAUSED', reply: '原研判会话已暂停并保留槽位；请提供 trace_id 查询状态或恢复原任务。', steps: [['RECEIVED', '检测到明确状态查询意图', '分类优先级高于槽位补充。', 'query_status。', '不混合两个任务上下文。', '上下文切换如何防止串单？'], ['CONTEXT_PAUSED', '暂停原研判槽位', '保存原 sample_id/缺失字段。', 'session 状态=paused_for_status_query。', '状态查询须提供 UUID trace_id。', '为什么不能猜任务状态？']] }),
  buildCase({ id: 'security-normal', domain: 'security', title: '安全运营｜授权扫描降噪复核', user: '研判告警 A-1001：授权扫描时段的 DNS 活动', outcome: 'NEEDS_REVIEW', severity: 'low', verification: 'local-tested', reply: '规则命中授权扫描条件，建议抑制但必须人工复核并留存处置结果。', steps: [...securityBase, ['LLM_SUMMARIZE', '生成证据说明', 'LLM 只能解释既定 policy decision。', 'action=suppress_with_review。', '模型不能改写动作。', 'LLM 在安全运营中承担什么角色？'], ['DECIDE_ACTION', '输出待复核降噪建议', '规则要求 evidenceRequired 全部存在。', 'matchedRuleId=fp_dns_001；score=0.85。', '无证据不可自动抑制。', '评分阈值来自哪里？'], ['PERSIST_RESULT', '经 OctoBus 记录处置结果', '调用 RecordTriageResult。', 'recordId 与 trace_id。', '失败转人工记录，不丢失结论。', '结果如何审计？'], ['COMPLETED', '完成状态快照', '按 sequence 写 SQLite。', '状态历史可回放。', '不保存原始日志或私有 IOC。', '重启后状态是否保留？']] }),
  buildCase({ id: 'security-ioc', domain: 'security', title: '安全运营｜私有威胁证据命中升级', user: '研判告警 A-private：发现私有证据关联', outcome: 'ESCALATE', severity: 'high', verification: 'local-tested', reply: '命中私有威胁证据，已升级为人工案件；界面仅展示 evidence_id，不展示 IOC 原文。', steps: [...securityBase, ['DECIDE_ACTION', '升级人工案件', '关联命中优先于误报降噪规则。', 'matchedCount=1；source_type=APT_IP。', '只显示 evidence_id，IOC 不入状态/LLM。', '私有知识库如何避免泄露？'], ['PERSIST_RESULT', '记录升级结果', '通过 RecordTriageResult 留痕。', 'trace_id 与 recordId。', '不执行自动封禁。', '为什么命中 IOC 不自动封禁？'], ['COMPLETED', '完成待人工调查案件', '留存状态链路。', '人工调查动作。', '最小权限与人工决策。', '自动化边界在哪里？']] }),
  buildCase({ id: 'security-record-fail', domain: 'security', title: '安全运营｜处置记录失败转人工', user: '研判告警 A-1001，模拟处置留存失败', outcome: 'MANUAL_RECORD_REQUIRED', severity: 'medium', verification: 'local-tested', reply: '规则结论已形成，但记录能力失败；已转人工留存，避免丢失审计责任。', steps: [...securityBase, ['DECIDE_ACTION', '生成确定性处置建议', '规则结果保持不可变。', 'action=suppress_with_review。', 'LLM 不改动作。', '异常时是否仍保留决策依据？'], ['PERSIST_RESULT', 'RecordTriageResult 失败', '捕获能力写入异常。', 'recorded=false。', '不能假称已落库。', '如何防止审计缺口？'], ['NEED_HUMAN', '要求人工补录', '状态改为 manual_record_required。', '失败原因与 trace_id。', '不重试未知副作用写操作。', '人工如何补录并关联 trace？']] })
];
